### PR TITLE
Attempt at wording things for unavailable radar

### PR DESCRIPTION
**Pull request by nonrenewable**
The original wording was "Dark Sky covers the given location, but all stations are currently unavailable." which I can also keep if you all prefer for an error summary! (I actually just wanted to make sure i understand how translations get built first and now can do anything 😁 )

### CODE REVIEW

**Comment by ironwallaby** [comment]
I would perhaps favor the English wording "Next hour forecasts are temporarily unavailable due to all nearby radar stations being offline."

**Comment by nonrenewable** [comment]
I'm totally on board with that! @novall @cailees @w1bw Please let me know if you're on board with @ironwallaby 's suggestion or prefer something slightly different since i'm not choosy

**Comment by novall** [comment]
I'm on board 👍

**Comment by nonrenewable** [comment]
per @novall and @w1bw we currently have a slightly denser wording of `"Next Hour: Temporarily unavailable.\n(Radar station offline)"` so will touch base with @cailees tomorrow to get her opinion and see what makes sense for display purposes

**Comment by nonrenewable** [comment]
I merge squashed this to `master`. Unsure how to tell github so closing.

**Pull request closed without merging**
