### PR TITLE
Improved Cornish translation of offline radar stations

### PR DESCRIPTION
**Pull request by steronydh**
Replacement for previous withdrawn pull request,

### CODE REVIEW

**Comment by ironwallaby** [comment]
Thank you! Please hold off just a bit, we are going to be reworking this and adding a couple other error messages related to offline radar stations, so it might be best to do it all at once!

**Comment by ironwallaby** [comment]
(Also, thanks for being _super on top_ of maintaining the Cornish translation 😸)

**Comment by steronydh** [comment]
It's a pleasure! And thank you for this great resource - your method of producing dynamic translations should be an inspiration to others.

**Comment by ironwallaby** [comment]
OK, we have the English version ready! These are the lines needing translation: https://github.com/darkskyapp/translations/blob/master/lib/lang/en.js#L166-L171

And here are the new tests: https://github.com/darkskyapp/translations/blob/master/test_cases/en.json#L262-L267

Documentation can be found in the README! https://github.com/darkskyapp/translations#status-information

**Comment by steronydh** [comment]
@ironwallaby I've just read online that the API will be closed down at the end of 2021 following the acquisition of DarkSky by Apple - I'm sad to hear that. I understand the commercial decision of course, but the loss of the translations will be a big blow to several minority languages.

Are there any alternatives you can think of?

Thanks for all your support over the years! :)

**Pull request closed without merging**
