### PR TITLE
Hebrew translation file

### PR DESCRIPTION
**Pull request by nire0510**

### CODE REVIEW

**Comment by ironwallaby** [comment]
Thanks! Could you also attach a `/test_cases/he.json` as well so we have tests to verify that the translation works?

**Comment by nire0510** [comment]
@ironwallaby no problem! on it. Would you like me to submit a new PR when it's ready?

**Comment by ironwallaby** [comment]
@nire0510 Or simply update this one! :+1:

**Comment by ironwallaby** [comment]
An [alternate Hebrew translation](https://github.com/darkskyapp/translations/pull/171) was merged in, so I'm closing this. Please let us know if you catch any bugs!

**Pull request closed without merging**
