### PR TITLE
Add support for Farsi (Persian) Translations.

### PR DESCRIPTION
**Pull request by amirhoseinaliakbarian**

### CODE REVIEW

**Comment by amirhoseinaliakbarian** [comment]
It looks there is problem in CI.

The tests are passing successfully on local. but they are not running at all on travis

**Comment by ironwallaby** [comment]
Can you try rebasing against master? That issue should now be fixed.

**Comment by ironwallaby** [comment]
Actually, I managed to confirm this locally myself. I'll manually merge it and update here when complete.

**Comment by ironwallaby** [comment]
This is live in 2.3.0. Thank you, and sorry for the delay in checking into the test issues!

**Comment by amirhoseinaliakbarian** [comment]
Ok, Thanks a lot.

**Pull request closed without merging**
