### PR TITLE
2nd update hr.js

### PR DESCRIPTION
**Pull request by cro-tomo**
some light improvements

### CODE REVIEW

**Comment by ironwallaby** [comment]
Thank you! Could you please adjust `/test_cases/hr.json` as well to match, so the tests will pass?

**Comment by cro-tomo** [comment]
I just did... and re arrange some phrases on both files...

**Comment by cro-tomo** [comment]
I don't know what I am doing wrong but I can't match hr.json on test_cases
with original one :(
after I edit translation i press PROPOSE FILE CHANGE and what then? I have
to wait for admin to check and approve or what?

pet, 7. pro 2018. u 15:42 Jay LaPorte <notifications@github.com> napisao je:

**Comment by ironwallaby** [comment]
I merged #195 into this locally, and everything _mostly_ passes! I only get the following error:

```
  1) translations
       languages
         hr
           should translate ["sentence",["with",["over-weekend","mixed-precipitation"],["temperatures-rising",["celsius",32],"thursday"]]] to "Različite padaline tijekom vikenda, s temperaturom u porastu do 32°C u četvrtak.":

      AssertionError [ERR_ASSERTION]: 'Mješavina padalina tijekom vikenda, s temperaturom u porastu do 32°C u četvrtak.' === 'Različite padaline tijekom vikenda, s temperaturom u porastu do 32°C u četvrtak.'
      + expected - actual

      -Mješavina padalina tijekom vikenda, s temperaturom u porastu do 32°C u četvrtak.
      +Različite padaline tijekom vikenda, s temperaturom u porastu do 32°C u četvrtak.
```

Which of those two are correct?

**Comment by ironwallaby** [comment]
Actually, it looks like `Mješavina padalina` is the correct one, since this is literally the change you made originally. I'll patch that in...

**Comment by ironwallaby** [comment]
Released as https://github.com/darkskyapp/translations/releases/tag/v2.4.3

**Pull request merged**
