### PR TITLE
Add Vietnamese translation

### PR DESCRIPTION
**Pull request by jeffbyrnes**
Courtesy of @phungdoanh, this gives us a single PR that includes the translation & its tests.

Closes #178 
Closes #184
Closes #185 
Closes #187

### CODE REVIEW

**Comment by jeffbyrnes** [comment]
@nhatientri & @vtabk2, you previously worked on #145 and had what looks like meaningful feedback. Would you mind reviewing this translation by @phungdoanh as well? It’d be great to get this translation in!

**Comment by phungdoanh** [comment]
When you can merger it to master?
Thanks and best regards

**Comment by jeffbyrnes** [comment]
@phungdoanh, I’d love to get some additional review on this from @nhatientri & @vtabk2, since none of us here at Dark Sky speak or read Vietnamese.

**Comment by ironwallaby** [comment]
Additionally, the tests need to pass. You can click the little ❌ above to see what's wrong with them.

**Comment by ironwallaby** [comment]
I'm closing this for the time being as it appears that the work on this is dead. Please reopen if otherwise!

**Pull request closed without merging**
