### PR TITLE
Add Irish translation and tests

### PR DESCRIPTION
**Pull request by MacMhicheil**

### CODE REVIEW

**Comment by MacMhicheil** [comment]
I'm a bit puzzled why this is failing. The log says that it is expecting "Dé Céadaoin seo chugainn" for "next Wednesday" but it is getting "Céadaoin seo chugainn" instead. I've double checked both the language file and the test file and I have "Dé Céadaoin seo chugainn" in both.

**Comment by ironwallaby** [comment]
I see the `join_with_shared_prefix()` function in your translation. Is this appropriate?

(It's intended purpose, in English, is to make "next Wednesday and next Thursday" turn into "next Wednesday and Thursday", or something like that. It might not be appropriate to every language.)

**Comment by MacMhicheil** [comment]
Thanks again for your help @ironwallaby!

**Comment by ironwallaby** [comment]
Thank you! This looks good, I'll get it merged in.

**Pull request merged**
